# Get pnpm packages
FROM node:18-alpine AS dependencies
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# Rebuild the source code only when needed
FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

# Copy in the .env file generated by the Cloud Build pipeline
# Next.js will automatically load this during build
COPY .env .env

# Build the application
# Next.js automatically reads .env files and makes NEXT_PUBLIC_* vars available
RUN npm install -g pnpm && \
    echo "🔨 Building Next.js application..." && \
    echo "📋 Checking .env file:" && \
    if [ -f .env ]; then \
      echo "✅ .env file exists with $(wc -l < .env) lines"; \
      echo "📋 Variables in .env:" && \
      cat .env | cut -d= -f1 | grep NEXT_PUBLIC || echo "⚠️  No NEXT_PUBLIC vars found"; \
    else \
      echo "❌ ERROR: .env file not found!"; \
      exit 1; \
    fi && \
    pnpm build

# Production image, copy all the files and run next
FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV production

# Install pnpm globally as root before switching users
RUN npm install -g pnpm

# Create a startup script that handles Docker and Cloud Run
RUN echo '#!/bin/sh' > /app/start.sh && \
    echo 'set -e' >> /app/start.sh && \
    echo 'echo "🚀 Starting Next.js application..."' >> /app/start.sh && \
    echo 'if [ -z "$PORT" ]; then' >> /app/start.sh && \
    echo '  export PORT=8080' >> /app/start.sh && \
    echo '  echo "⚠️  PORT not set, defaulting to $PORT"' >> /app/start.sh && \
    echo 'else' >> /app/start.sh && \
    echo '  echo "✅ PORT is set to $PORT"' >> /app/start.sh && \
    echo 'fi' >> /app/start.sh && \
    echo 'exec pnpm next start -p $PORT' >> /app/start.sh && \
    chmod +x /app/start.sh

# Copy the environment file for runtime variables (if any)
COPY --from=builder /app/.env /app/.env

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# Copy built application
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./next.config.ts

# Make sure nextjs user can access the start script
RUN chown nextjs:nodejs /app/start.sh

USER nextjs
EXPOSE 8080

# Use the startup script as the entry point
CMD ["/app/start.sh"]