export const avatars = [
  {
    id: 1,
    name: "Chapter 1",
    specialty: "Diabetes Mellitus",
    looks: "Diabetes Mellitus",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Diabetes specialist focused on Type 1, Type 2, and gestational diabetes management",
    knowledgeId: "2ff4f19c833546a5931e7491f3d67c4f",
  },
  {
    id: 2,
    name: "Chapter 2",
    specialty: "Lipid Disorders",
    looks: "Lipid Disorders",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Expert in dyslipidemia, genetic lipid disorders, and lipodystrophy syndromes",
    knowledgeId: "4e101a66a74542cf9142d943700e602d",
  },
  {
    id: 3,
    name: "Chapter 3",
    specialty: "Obesity and Nutrition",
    looks: "Obesity and Nutrition",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Obesity medicine specialist with expertise in bariatric surgery and eating disorders",
    knowledgeId: "d6c3602f749c422695d17a7f98312693",
  },
  {
    id: 4,
    name: "Chapter 4",
    specialty: "Pituitary and Neuroendocrinology",
    looks: "Pituitary and Neuroendocrinology",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Pituitary surgeon specializing in adenomas, Cushing's, and acromegaly",
    knowledgeId: "11a6c9bb8fd54954841e953f79bd6a67",
  },
  {
    id: 5,
    name: "Chapter 5",
    specialty: "Thyroid",
    looks: "Thyroid",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Thyroid specialist managing hyperthyroidism, hypothyroidism, and thyroid cancer",
    knowledgeId: "73efcd7c29b2402e8e0e679e7d39325a",
  },
  {
    id: 6,
    name: "Chapter 6",
    specialty: "Parathyroid, Calcium and Bone",
    looks: "Parathyroid, Calcium and Bone",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Bone metabolism expert focusing on osteoporosis and parathyroid disorders",
    knowledgeId: "02a5b8aa8f3d40ad8d68ec2db975d256",
  },
  {
    id: 7,
    name: "Chapter 7",
    specialty: "Adrenal",
    looks: "Adrenal",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Adrenal specialist treating Addison's disease, Cushing's, and pheochromocytoma",
    knowledgeId: "f5802d9ec080447aa46927d486c1626c",
  },
  {
    id: 8,
    name: "Chapter 8",
    specialty: "Reproductive Endocrinology",
    looks: "Reproductive Endocrinology",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Reproductive endocrinologist specializing in PCOS, infertility, and menopause",
    knowledgeId: "38858f0ba61943258be7b2267155966e",
  },
  {
    id: 9,
    name: "Chapter 9",
    specialty: "Electrolytes and Fluid Balance",
    looks: "Electrolytes and Fluid Balance",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Electrolyte specialist managing hyponatremia, SIAD, and fluid disorders",
    knowledgeId: "34166f2ce07c4267ae3fba558281ce23",
  },
  {
    id: 10,
    name: "Chapter 10",
    specialty: "Neuroendocrine Tumours",
    looks: "Neuroendocrine Tumours",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "NET specialist treating pancreatic, pulmonary, and GI neuroendocrine tumors",
    knowledgeId: "ece819af8e654755937f81913c4feda2",
  },
  {
    id: 11,
    name: "Chapter 11",
    specialty: "Inherited Endocrine Syndromes",
    looks: "Inherited Endocrine Syndromes",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Genetic endocrinologist specializing in MEN syndromes and familial disorders",
    knowledgeId: "a84bada8b31a4400bd2b0e9cc3fa3bcb",
  },
  {
    id: 12,
    name: "Chapter 12",
    specialty: "Autoimmune Polyend. Syndromes",
    looks: "Autoimmune Polyend. Syndromes",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Autoimmune specialist treating polyglandular syndromes and IgG4 disease",
    knowledgeId: "f4c10e4180ac4d4bbbf4c9d78b3532ac",
  },
  {
    id: 13,
    name: "Chapter 13",
    specialty: "Treatment-Induced Dysfunction",
    looks: "Treatment-Induced Dysfunction",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Oncology endocrinologist managing drug-induced endocrine complications",
    knowledgeId: "f8ec9e92efa449db9c22e8bd04d8c919",
  },
  {
    id: 14,
    name: "Chapter 14",
    specialty: "Endocrine-Disrupting Chemicals",
    looks: "Endocrine-Disrupting Chemicals",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Environmental endocrinologist studying chemical effects on hormone systems",
    knowledgeId: "2a2a8ea5208b49a4b8a4d5a9ce8dd5f0",
  },
  {
    id: 15,
    name: "Chapter 15",
    specialty: "Diagnostic Techniques",
    looks: "Diagnostic Techniques",
    image: "/modules/avatar/alessandra.webp?height=200&width=200",
    description: "Diagnostic specialist in hormone testing, imaging, and molecular genetics",
    knowledgeId: "5dd948b0a95c431a934ef588a791a82a",
  }
];